name: Weather Data Aggregation

on:
  schedule:
  - cron: "10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    env:
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      WEATHERSTACK_API_KEY: ${{ secrets.WEATHERSTACK_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.SEC_GITHUB_TOKEN }}

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Set up environment variables
        run: |
          echo "OPENWEATHERMAP_API_KEY=${{ secrets.OPENWEATHERMAP_API_KEY }}" >> $GITHUB_ENV
          echo "WEATHERSTACK_API_KEY=${{ secrets.WEATHERSTACK_API_KEY }}" >> $GITHUB_ENV


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute data aggregation script
        run: |
          python weather_aggregator.py

      - name: Commit files
        run: |
          git config user.email ${{ secrets.EMAIL }} 
          git config user.name ${{ secrets.USERNAME }} 
          git remote add private_repo https://${{ secrets.SEC_GITHUB_TOKEN }}@github.com/Greviansonula/Data-Aggregation.git
          git add .
          git commit -a -m "1.1.1.1 $(date)"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SEC_GITHUB_TOKEN }} 
          branch: ${{ github.ref }}
