name: Weather Data Aggregation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      WEATHERSTACK_API_KEY: ${{ secrets.WEATHERSTACK_API_KEY }}

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Set up environment variables
        run: |
          echo "OPENWEATHERMAP_API_KEY=${{ secrets.OPENWEATHERMAP_API_KEY }}" >> $GITHUB_ENV
          echo "WEATHERSTACK_API_KEY=${{ secrets.WEATHERSTACK_API_KEY }}" >> $GITHUB_ENV


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute data aggregation script
        run: |
          python weather_aggregator.py

      - name: Commit files
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.USERNAME }}
          git add -A
          git commit -m "Update aggregated weather data" -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.SEC_GITHUB_TOKEN }}
          branch: master
